name: os
description: bigjazzsound's workstation OS
base-image: ghcr.io/ublue-os/sericea-main
image-version: 39

modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - awscli2
      - bcc
      - cmake
      - fd-find
      - fish
      - fzf
      - gcc
      - gcc-c++
      - gdb
      - gh
      - glibc-devel
      - golang
      - htop
      - jq
      - kitty
      - libadwaita
      - libvirt
      - make
      - mpv
      - nmap
      - npm
      - pam-u2f
      - pipx
      - podman-remote
      - pwgen
      - python3-pip
      - ripgrep
      - rsync
      - sipcalc
      - tailscale
      - virt-install
      - virt-manager
      - wireguard-tools
      - wlsunset
      - yubikey-manager
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - justfiles # add "!include /usr/share/ublue-os/just/bling.just"
                  # in your custom.just (added by default) or local justfile
      - nix-installer # shell shortcuts for determinate system's nix installers
      - ublue-os-wallpapers
      # - ublue-update # https://github.com/ublue-os/ublue-update
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm

  - type: yafti
    custom-flatpaks:
      - Bitwarden: com.bitwarden.desktop
      - Discord: com.discordapp.Discord
      - Slack: com.slack.Slack
      - Steam: com.valvesoftware.Steam
      - SteamLink: com.valvesoftware.SteamLink
      - YubiOATH: com.yubico.yubioath
      - Lutris: net.lutris.Lutris
      - Flameshot: org.flameshot.Flameshot

  - type: script
    scripts:
      - signing.sh
