---
name: os
description: bigjazzsound's workstation OS
base-image: ghcr.io/ublue-os/sericea-main
image-version: 39

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      - https://download.docker.com/linux/fedora/docker-ce.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      - awscli2
      - bcc
      - clang
      - cmake
      - composer-cli
      - docker-ce-cli
      - eza
      - fd-find
      - fish
      - fzf
      - gdb
      - gh
      - git-credential-libsecret
      - glibc-devel
      - golang
      - htop
      - jq
      - kitty
      - libadwaita
      - libvirt
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - lld
      - make
      - mkosi
      - mpv
      - nmap
      - nodejs-npm
      - osbuild-composer
      - pam-u2f
      - pipx
      - podman-remote
      - pwgen
      - python3-devel
      - python3-pip
      - qemu
      - qemu-kvm
      - ripgrep
      - rsync
      - sipcalc
      - tailscale
      - virt-install
      - virt-manager
      - virt-viewer
      - wireguard-tools
      - wlsunset
      - yubikey-manager
    remove:
      - firefox
      - firefox-langpacks

  - type: signing
